<?php

/**
 * @file
 * Code for the music_extras module.
 */

require_once 'includes/music_extras.helper.inc';

/**
 * Implements hook_preprocess_page().
 */
function music_extras_preprocess_page(&$variables) {
  // Add status block to the front page.
  if (drupal_is_front_page()) {
    $block = block_load('formblock', 'status');
    $renderable_block =  _block_get_renderable_array(_block_render_blocks(array($block)));
    $status_formblock = array(
      'status_formblock' => array(
        '#markup' => drupal_render($renderable_block),
      ),
    );
    array_unshift($variables['page']['content'], $status_formblock);
  }
}

/**
 * Implements hook_token_info().
 */
function music_extras_token_info() {
  $info['tokens']['user']['number-of-posts'] = array(
    'name' => t('Number of posts'),
    'description' => t('Number of posts by the current user.'),
  );

  return $info;
}

/**
 * Implements hook_tokens().
 */
function music_extras_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();

  if ($type == 'user') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'number-of-posts':
          $replacements[$original] = music_extras_number_of_posts();
          break;
      }
    }
  }

  return $replacements;
}
